### PR TITLE
Add Pathological to markdown/index.md

### PR DESCRIPTION
**Pull request by jjgignac**

### CODE REVIEW

**Comment by sauliuz** [comment]
hi @jjgignac, thanks for pull request, but we do not add links to app stores on mobilegap.net
only links to the open source code repos. would be great if you can edit your pull request.

**Comment by jjgignac** [comment]
Will do.  I'm sorry if I missed the documentation to that effect.  Thanks
for letting me know.

I presume you've considered changing that policy?  It could potentially be
beneficial to all your participants.

JP

**Comment by jjgignac** [comment]
I pushed the change.

JP

**Comment by sauliuz** [comment]
you didn't miss it, we actually don't have it documented :) 
for now, we just maintain the link to source code + short description structure, but in the future might rethink it.

**Pull request merged**
